module.exports = function (sequelize, DataTypes) {
    return sequelize.define('schemereturns', {
        schid: {
            type: DataTypes.INTEGER,
            allowNull: true,
            unique: true
        },
        '1Day': DataTypes.FLOAT,
        '7Day': DataTypes.FLOAT,
        '15Day': DataTypes.FLOAT,
        '30Day': DataTypes.FLOAT,
        '3Month': DataTypes.FLOAT,
        '6Month': DataTypes.FLOAT,
        '1Year': DataTypes.FLOAT,
        '2Year': DataTypes.FLOAT,
        '3Year': DataTypes.FLOAT,
        '5Year': DataTypes.FLOAT,
        '10Year': DataTypes.FLOAT,
        D1Rank: DataTypes.FLOAT,
        D7Rank: DataTypes.FLOAT,
        D15Rank: DataTypes.FLOAT,
        D30Rank: DataTypes.FLOAT,
        M3Rank: DataTypes.FLOAT,
        M6Rank: DataTypes.FLOAT,
        Y1Rank: DataTypes.FLOAT,
        Y2Rank: DataTypes.FLOAT,
        Y3Rank: DataTypes.FLOAT,
        Y5Rank: DataTypes.FLOAT,
        Y10Rank: DataTypes.FLOAT,
        D1Quarter: DataTypes.CHAR(1),
        D7Quarter: DataTypes.CHAR(1),
        D15Quarter: DataTypes.CHAR(1),
        D30Quarter: DataTypes.CHAR(1),
        M3Quarter: DataTypes.CHAR(1),
        M6Quarter: DataTypes.CHAR(1),
        Y1Quarter: DataTypes.CHAR(1),
        Y2Quarter: DataTypes.CHAR(1),
        Y3Quarter: DataTypes.CHAR(1),
        Y5Quarter: DataTypes.CHAR(1),
        Y10Quarter: DataTypes.CHAR(1),
        sinceInceptionReturn: DataTypes.FLOAT,
        '1YearSIPReturn': DataTypes.DECIMAL(10,4),
        '3YearSIPReturn': DataTypes.DECIMAL(10,4),
        '5YearSIPReturn': DataTypes.DECIMAL(10,4),
        '10YearSIPReturn': DataTypes.DECIMAL(10,4),
        '15YearSIPReturn': DataTypes.DECIMAL(10,4),
        '20YearSIPReturn': DataTypes.DECIMAL(10,4),
        sinceInceptionSIPReturn: DataTypes.DECIMAL(10,4),
    }, {
        tableName: 'schemereturns'
    })
}